name: Deploy to Azure Web App (OIDC)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for OIDC
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Azure with OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true
        enable-oidc: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Azure CLI
      run: |
        python -m pip install --upgrade pip
        pip install azure-cli

    - name: Deploy to Web App
      env:
        AZURE_RESOURCE_GROUP: my-app-service-group
        AZURE_WEBAPP_NAME: my-sre-app-rav
      run: |
        # Use `az webapp deployment` which supports zip deploy or runtime-specific deployment
        zip -r app.zip . -x .git/**\n        az webapp deploy --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_WEBAPP_NAME" --src-path app.zip
