name: Smoke tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install test requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r UnitTest/requirements.txt

    - name: Run smoke tests
      env:
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        pytest -q -m smoke UnitTest
